import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import bgimg from '@/assets/bg-milady.jpeg'
import Grid from '@mui/material/Grid';
import Grid2 from '@mui/material/Unstable_Grid2'; // Grid version 2

const inter = Inter({ subsets: ['latin'] })

export default function Home() {



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <p className={styles.description}>
                    milady</p>
                <img src="/bg-milady.jpeg" width="50%">
                </img>
                <p className={styles.description}>
                    now on bitcoin
                </p>
                <br></br>
                <hr></hr>
                <br></br>
                <div className={styles.card}>
                    <p className={styles.description}>
                        <span><a href='https://ordinals.com'>explorer</a></span>
                        &nbsp; || &nbsp;
                        <span><a href='https://ordinals.com'>twitter</a></span>
                        &nbsp; || &nbsp;
                        <span><a href='https://twitter.com/miladymaker'>milady maker</a></span>
                        &nbsp; || &nbsp;
                        <span><a href='https://www.torproject.org/download/'>download tor</a></span>
                    </p>
                </div>
                <br></br>
                <div className={styles.card}>
                    <p className={styles.description}>
                        bitcoin miladies are <span><a href='https://ordinals.com'>ordinal NFTs</a></span> inscribed on the Bitcoin blockchain by <span><a href='https://twitter.com/redbottomdancer'>happy feet 🌸</a></span> (with the help of a boy dev)
                        <br></br>
                        <br></br>
                        <center>i hope you enjoy them</center>
                    </p>
                </div>
                <br></br>
                {/* <div className={styles.card}>
                    <div className={styles.grid}>
                        <img src="https://ordinals.com/content/3bbadeddccd5cddd4d95671199789a7fe217e40f203630edbcfe72e2939acd0ai0" width="80%"></img>
                        <img src="/bg-milady.jpeg" width="50%"></img>
                        <img src="/bg-milady.jpeg" width="50%"></img>
                    </div>
                </div> */}

            </main>
        </>
    )
}
