import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Milady Ordinals</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <p className={styles.description}>
                    milady</p>
                <img src="/bg-milady.jpeg" height="500vh">
                </img>
                <br></br>
                <br></br>
                <p className={styles.description}>
                    now on bitcoin
                </p>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <div className={styles.card}>
                    <center>
                        <p className={styles.description}>
                            <span><a href='https://openordex.org/collection?slug=milady'>explorer</a></span>
                            &nbsp; // &nbsp;
                            <span><a href='https://twitter.com/ordinalmilady'>twitter</a></span>
                            &nbsp; // &nbsp;
                            <span><a href='https://remilia.org/'>remilia</a></span>
                            &nbsp; // &nbsp;
                            <span><a href='https://www.torproject.org/download/'>download tor</a></span>
                        </p>
                    </center>
                </div>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <div className={styles.card}>
                    <center>
                        <p className={styles.description}>
                            bitcoin miladies are <span><a href='https://ordinals.com'>ordinal NFTs</a></span> inscribed on the Bitcoin blockchain by <span><a href='https://twitter.com/redbottomdancer'>happy feet 🌸</a></span> (with the help of a boy dev)
                        </p>
                        <br></br>
                        <br></br>
                        <br></br>
                        <br></br>
                        <p>i hope you enjoy them</p>
                    </center>

                </div>
            </main>
        </>
    )
}
